# Generated by Django 2.1.7 on 2019-03-08 19:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogComments',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for the comments.', primary_key=True, serialize=False)),
                ('comment', models.CharField(max_length=200)),
                ('comment_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['blogpost', 'comment_date'],
            },
        ),
        migrations.CreateModel(
            name='Blogger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('occupation', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateTimeField(auto_now=True)),
                ('blogger', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kaseys_blog.Blogger')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a topic.', max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='blogpost',
            name='topic',
            field=models.ManyToManyField(help_text='Select a topic for this post.', to='kaseys_blog.Topic'),
        ),
        migrations.AddField(
            model_name='blogcomments',
            name='blogpost',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kaseys_blog.BlogPost'),
        ),
    ]
