# Generated by Django 2.1.7 on 2019-03-08 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kaseys_blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogComments',
            new_name='BlogComment',
        ),
    ]
