# Generated by Django 2.1.7 on 2019-03-08 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kaseys_blog', '0002_auto_20190308_1510'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='date',
            new_name='postdate',
        ),
    ]
