# Generated by Django 2.1.7 on 2019-03-09 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaseys_blog', '0003_auto_20190308_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='blog_body',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
