# Generated by Django 2.1.7 on 2019-03-09 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaseys_blog', '0005_auto_20190309_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='blog_body',
            field=models.TextField(help_text='Type your blog here.', max_length=1000, null=True),
        ),
    ]
