# Generated by Django 2.1.7 on 2019-03-10 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaseys_blog', '0006_auto_20190309_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcomment',
            name='comment',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='blogcomment',
            name='comment_date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
